service: pyapi-practice

provider:
  name: aws
  stage: prod
  region: ap-northeast-1
  deploymentBucket: pyapi-practice # デプロイ時に使うS3 あまり増やすと上限に引っかかるのでこれだけにした
  logRetentionInDays: 30 # Cloudwatchのログ保存期間 無限課金防止

functions:
  index:
    image: "${ssm:AccountID}.dkr.ecr.ap-northeast-1.amazonaws.com/${ssm:MangumRepository}" # ダイジェスト込み
    events:
      - http:
          integration: lambda-proxy
          path: /{proxy+}
          method: ANY
          cors: true
