service: sql-api-test

provider:
  name: aws
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSQuicksightAthenaAccess"
  stage: prod
  region: ap-northeast-1
  deploymentBucket: athena-api-kii # デプロイ時に使うS3 あまり増やすと上限に引っかかるのでこれだけにした
  logRetentionInDays: 30 # Cloudwatchのログ保存期間 無限課金防止

functions:
  index:
    image: "${ssm:AccountID}.dkr.ecr.ap-northeast-1.amazonaws.com/${ssm:SqlApiRepository}" # ダイジェスト込み
    events:
      - http:
          integration: lambda-proxy
          path: /{proxy+}
          method: ANY
          cors: true
