service: sql-api-test

provider:
  name: aws
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSQuicksightAthenaAccess"
  environment:
    S3_BUCKET: athena-api-kii  # バケットを指定
  iam:
    role:
      statements:
        # S3の指定バケット上のオブジェクトの入出力を許可
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:GetBucketLocation
            - s3:GetObject
            - s3:ListBucket
            - s3:ListBucketMultipartUploads
            - s3:ListMultipartUploadParts
            - s3:AbortMultipartUpload
            - s3:CreateBucket
            - s3:PutObject
          Resource:
            - arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*
        # CloudWatchにログ出力を許可
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - "*"
  stage: prod
  region: ap-northeast-1
  deploymentBucket: athena-api-kii # デプロイ時に使うS3 あまり増やすと上限に引っかかるのでこれだけにした
  logRetentionInDays: 30 # Cloudwatchのログ保存期間 無限課金防止

functions:
  index:
    image: "${ssm:AccountID}.dkr.ecr.ap-northeast-1.amazonaws.com/${ssm:SqlApiRepository}" # ダイジェスト込み
    events:
      - http:
          integration: lambda-proxy
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
